[package]
name = "bitcoin"
version = "0.1.0"
authors = ["Interlay Ltd <dominik@interlay.io>"]
edition = "2018"

[features]
default = ['std']
std = [
	'codec/std',
	'sp-core/std',
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = '2.0.0'

[dependencies.bitcoin-spv]
default-features = false
git = 'https://gitlab.com/interlay/bitcoin-spv.git'
package = 'bitcoin-spv'
version = '0.1.0'

