[package]
name = "bitcoin"
version = "0.1.0"
authors = ["Dominik Harz <dominik@interlay.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ['std']
std = [
    'codec/std',
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.bitcoin-spv]
default-features = false
git = 'https://gitlab.com/interlay/bitcoin-spv.git'
package = 'bitcoin-spv'
version = '0.1.0'

